# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/azure-images

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'scripts\AzureLogin.ps1'
    arguments: '-CloudAccount $azureUserId'
    workingDirectory: 'scripts\'

# Needs to input the Resource group and outputs the image name
#- task: PowerShell@2
#  inputs:
#    filePath: 'scripts\bake-scalable-azure-14-0.ps1'
#    workingDirectory: 'scripts\'

# Needs to use hte image name from the previous build task
# Implement using Pester
#- task: PowerShell@2
#  inputs:
#    filePath: 'Tests\TestImage.ps1'
#    arguments: '-ImgName "w12r2d-14-2-10" -CloudName $CloudName'
#    workingDirectory: 'Tests\'